// <auto-generated />
using System;
using CarRental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRental.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRental.Domain.Entities.Car", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").HasColumnName("id");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Color").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)").HasColumnName("color");
                b.Property<string>("LicensePlate").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasColumnName("license_plate");
                b.Property<int>("ModelGenerationId").HasColumnType("int").HasColumnName("model_generation_id");
                b.HasKey("Id");
                b.HasIndex("ModelGenerationId");
                b.ToTable("cars");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.CarModel", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").HasColumnName("id");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("BodyType").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)").HasColumnName("body_type");
                b.Property<string>("Class").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)").HasColumnName("class");
                b.Property<string>("DriveType").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)").HasColumnName("drive_type");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)").HasColumnName("name");
                b.Property<int>("SeatsCount").HasColumnType("int").HasColumnName("seats_count");
                b.HasKey("Id");
                b.ToTable("car_models");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.Client", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").HasColumnName("id");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateOnly>("BirthDate").HasColumnType("date").HasColumnName("birth_date");
                b.Property<string>("FullName").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)").HasColumnName("full_name");
                b.Property<string>("LicenseNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasColumnName("license_number");
                b.HasKey("Id");
                b.ToTable("clients");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.ModelGeneration", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").HasColumnName("id");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<double>("EngineVolume").HasColumnType("float").HasColumnName("engine_volume");
                b.Property<int>("ModelId").HasColumnType("int").HasColumnName("model_id");
                b.Property<decimal>("RentalPricePerHour").HasColumnType("decimal(18,2)").HasColumnName("rental_price_per_hour");
                b.Property<string>("Transmission").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)").HasColumnName("transmission");
                b.Property<int>("Year").HasColumnType("int").HasColumnName("year");
                b.HasKey("Id");
                b.HasIndex("ModelId");
                b.ToTable("model_generations");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.Rental", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").HasColumnName("id");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("CarId").HasColumnType("int").HasColumnName("car_id");
                b.Property<int>("ClientId").HasColumnType("int").HasColumnName("client_id");
                b.Property<DateTime>("RentalDate").HasColumnType("datetime2").HasColumnName("rental_date");
                b.Property<int>("RentalHours").HasColumnType("int").HasColumnName("rental_hours");
                b.HasKey("Id");
                b.HasIndex("CarId");
                b.HasIndex("ClientId");
                b.ToTable("rentals");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.Car", b =>
            {
                b.HasOne("CarRental.Domain.Entities.ModelGeneration", "ModelGeneration")
                    .WithMany()
                    .HasForeignKey("ModelGenerationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("ModelGeneration");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.ModelGeneration", b =>
            {
                b.HasOne("CarRental.Domain.Entities.CarModel", "Model")
                    .WithMany()
                    .HasForeignKey("ModelId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Model");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.Rental", b =>
            {
                b.HasOne("CarRental.Domain.Entities.Car", "Car")
                    .WithMany()
                    .HasForeignKey("CarId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("CarRental.Domain.Entities.Client", "Client")
                    .WithMany()
                    .HasForeignKey("ClientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Car");
                b.Navigation("Client");
            });
#pragma warning restore 612, 618
        }
    }
}
