<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.RabbitMQ.Client" Version="9.3.1" />
    <PackageReference Include="AutoMapper" Version="15.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CarRental.Application.Contracts\CarRental.Application.Contracts.csproj" />
    <ProjectReference Include="..\CarRental.Infrastructure\CarRental.Infrastructure.csproj" />
  </ItemGroup>
</Project>
